// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ1njg1pVCpnDfHWPYueJPgwVs0jhG11g',
    appId: '1:332384831825:web:30b5cbcedc549b9cae2b70',
    messagingSenderId: '332384831825',
    projectId: 'twitter-project-c6',
    authDomain: 'twitter-project-c6.firebaseapp.com',
    databaseURL: 'https://twitter-project-c6-default-rtdb.firebaseio.com',
    storageBucket: 'twitter-project-c6.appspot.com',
    measurementId: 'G-Z3TYT0PKKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAStJT1f8G2YEwoQqfBsXhD1JNXMV8rX7w',
    appId: '1:332384831825:android:0da321c3194739baae2b70',
    messagingSenderId: '332384831825',
    projectId: 'twitter-project-c6',
    databaseURL: 'https://twitter-project-c6-default-rtdb.firebaseio.com',
    storageBucket: 'twitter-project-c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiKo_QoVO6vV9oYOXviA57EK-jN542dgE',
    appId: '1:332384831825:ios:8f07d2ef1af99950ae2b70',
    messagingSenderId: '332384831825',
    projectId: 'twitter-project-c6',
    databaseURL: 'https://twitter-project-c6-default-rtdb.firebaseio.com',
    storageBucket: 'twitter-project-c6.appspot.com',
    iosClientId: '332384831825-rvlp2ncltlg74q80keps04mpost76pi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.csci3100TwitterProjectC6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiKo_QoVO6vV9oYOXviA57EK-jN542dgE',
    appId: '1:332384831825:ios:8f07d2ef1af99950ae2b70',
    messagingSenderId: '332384831825',
    projectId: 'twitter-project-c6',
    databaseURL: 'https://twitter-project-c6-default-rtdb.firebaseio.com',
    storageBucket: 'twitter-project-c6.appspot.com',
    iosClientId: '332384831825-rvlp2ncltlg74q80keps04mpost76pi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.csci3100TwitterProjectC6',
  );
}
